on:
  workflow_call:
    inputs:
      git_token:
        required: false
        type: string
        description: 'Git access token'
      # tf_action:
      #   required: false
      #   type: string
      #   description: 'terraform action'
      # tfaction:
      #   required: false
      #   type: string
      #   description: 'terraform action' 
      #   default: 'apply'
runs:
  using: "composite"
  steps:
  - name: Terrafrom init
    run: |
      #echo "tf-action: ${{ inputs.tfaction }}"
      ls
      terraform init -backend-config="path=./terraform.tfstate"
    shell: bash  

  - name: Download Artifact
    uses: actions/download-artifact@v2
    shell: bash
    with:
      name: tfplan
      path: tfplan

  - name: Terrafrom apply
    shell: bash 
    run: |
      terraform apply -auto-approve tfplan
    env:
        TF_VAR_git_token: ${{ inputs.git_token }}

    # - name: GIT commit and push terraform state
    #   shell: bash
    #   run: |
    #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
    #     git config --global user.email "nsai.devops@gmail.com"
    #     git remote set-url origin https://nsai-devops:${{ inputs.git_token }}@github.com/nsai-devops/github_creation_tf_module.git
    #     git add terraform.tfstate
    #     git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
    #     git push
    #   env:
    #     CI_COMMIT_MESSAGE: Continuous Integration Terraform state
    #     CI_COMMIT_AUTHOR: nsai-devops          