on:
  workflow_call:
    inputs:
      git_token:
        required: false
        type: string
        description: 'Git access token'
      tf_action:
        required: false
        type: string
        description: 'terraform action'
      # tfaction:
      #   required: false
      #   type: string
      #   description: 'terraform action' 
      #   default: 'apply'
runs:
  using: "composite"
  steps:
  - name: Terrafrom init
    run: |
      echo "tf-action: ${{ inputs.tfaction }}"
      ls
      terraform init -backend-config="path=./terraform.tfstate"
    shell: bash  

  - name: Terrafrom validate
    run: |
      terraform validate
    shell: bash  

  - name: Terrafrom plan apply
    #if: ${{ inputs.tf_action }} == 'apply'
    run: |
      terraform plan -out=tfplan
    shell: bash  
    env:
      TF_VAR_git_token: ${{ inputs.git_token }}

  # - name: Terrafrom plan apply
  #   if: ${{ inputs.tf_action }} == 'destroy'
  #   run: |
  #     terraform plan -destroy -out=tfplan
  #   shell: bash  
  #   env:
  #     TF_VAR_git_token: ${{ inputs.git_token }}    

  - name: Upload Plan
    uses: actions/upload-artifact@v2
    with:
      name: tfplan
      path: tfplan          