on:
  workflow_call:
    inputs:
      git_token:
        required: false
        type: string
        description: 'Git access token'
runs:
  using: "composite"
  steps:
  - name: Terrafrom init
    run: |
      ls
      terraform init -backend-config="path=./terraform.tfstate"
    shell: bash  

  - name: Terrafrom validate
    run: |
      terraform validate
    shell: bash  

  - name: Terrafrom plan
    run: |
      terraform plan -out=plan.out
    shell: bash  
    env:
      TF_VAR_git_token: ${{ inputs.git_token }}

  - name: Upload Plan
    uses: actions/upload-artifact@v2
    with:
      name: plan
      path: ./plan.out          