on:
  workflow_call:
    inputs:
      git_token:
        required: false
        type: string
    # secrets:
    #   git_token:
    #     required: true
    #     type: string

runs:
  using: "composite"
  steps:
  - name: Terrafrom init
    run: |
      ls
      terraform init -backend-config="path=./terraform.tfstate"

  - name: Terrafrom validate
    run: |
      terraform validate
    # env:
    #   TF_VAR_git_token: ${{ secrets.git_token }}

  - name: Terrafrom plan
    run: |
      terraform plan
    env:
      TF_VAR_git_token: ${{ inputs.git_token }}      