on:
  workflow_call:
    inputs:
      git_token:
        required: false
        type: string
        description: 'Git access token'
      tf-action:
        required: true
        type: string
        description: 'terraform action'  
runs:
  using: "composite"
  steps:
  - name: Terrafrom init
    run: |
      ls
      terraform init -backend-config="path=./terraform.tfstate"
    shell: bash  

  - name: Terrafrom validate
    run: |
      terraform validate
    shell: bash  

  - name: Terrafrom plan apply
    if: ${{ inputs.tf-action }} == 'apply'
    run: |
      terraform plan -out=plan.out
    shell: bash  
    env:
      TF_VAR_git_token: ${{ inputs.git_token }}

  - name: Terrafrom plan apply
    if: ${{ inputs.tf-action }} == 'destroy'
    run: |
      terraform plan -destroy -out=plan.out
    shell: bash  
    env:
      TF_VAR_git_token: ${{ inputs.git_token }}    

  - name: Upload Plan
    uses: actions/upload-artifact@v2
    with:
      name: plan
      path: ./plan.out          