on:
  workflow_call:
    inputs:
      tfaction:
        required: false
    secrets:
      git_token:
        required: false
      tf_action:
        required: false 
jobs:
  Terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: list
      run: |
        echo "tf-action: ${{ inputs.tfaction }}"
        echo "tf-action: ${{ secrets.TF_ACTION }}"
        pwd
        ls
    - name: terraform plan-upload
      uses: nsai-devops/reusable-workflows/.github/actions/plan-upload@main
      with:
        tf_action: ${{ secrets.tf_action }}
        git_token: ${{ secrets.git_token }}


  # Terraform-apply-or-destroy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download Artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: plan
  #       path: ./plan.out
  #   - name: list
  #     run: |
  #       pwd
  #       ls
  #   # - name: terraform apply or destroy
  #   #   uses: nsai-devops/reusable-workflows/.github/actions/plan-upload@main
  #   #   with:
  #   #     git_token: ${{ secrets.git_token }}      

