on:
  workflow_call:
    secrets:
      git_token:
        required: true

jobs:
  Terraform-plan:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
    - name: list
      run: |
        pwd
        ls
    # - name: terraform plan-upload
    #   uses:   

