name: inputs test
on:
  workflow_call:
inputs:
  input_1:
    description: Input 1
    required: true
    default: default value
  input_2:
    description: Input 2
    required: false
jobs:
  inputs-test:
    runs-on: ubuntu-latest
    steps:
      - name: list
        run: |
          echo 'input-3: ${{ inputs.input_1 }}'
          echo 'input-4: ${{ inputs.input_2 }}'